description: Language Based Interactive Learning (imitation baseline)

target:
  vc: intvc
  cluster: rr1

environment:
  # image: dipendramisra/pytorch_branch_fairseq:1.0
  # image: dipendramisra/fairseq:1.0
  # image: nvidia/driver:440.64.00-ubuntu18.04-aws
  # image: pytorch/pytorch:1.4-cuda10.1-cudnn7-devel
  image: kracwarlock/unlik:1.4
  #image: microsoft_pytorch:v1.2.0_gpu_cuda9.0_py36_release_gpuenv_hvd0.16.2
  #registry: phillyregistry.azurecr.io

code:
  local_dir: $CONFIG_DIR/../..

data:
  local_dir: $CONFIG_DIR/../../data
  remote_dir: language_based_interactive_learning/data

search:
  job_template:
    name: search_{experiment_name:s}_{auto:s}
    sku: G1
    command:
    - pip install --user scikit-image
    - pip install --user jsonargparse
    - ls configs/
    - python train.py -config configs/experiments/imitation.yaml -student.model.learning_rate {learning_rate} -student.model.num_layers {num_layers} -student.model.hidden_size {hidden_size} -trainer.policy_mix.init_rate {policy_mix_rate} -student.model.word_embed_size {word_embed_size} -name imitation_{job_name} 
  type: grid
  max_trials: 10000
  params:
    - name: learning_rate
      spec: discrete
      values: [0.001, 0.0005]
    - name: num_layers
      spec: discrete
      values: [1, 2]
    - name: hidden_size
      spec: discrete
      values: [128, 256, 512]
    - name: word_embed_size
      spec: discrete
      values: [128, 256]
    - name: policy_mix_rate
      spec: discrete
      values: [0.0, 1.0]
